### ISSUE TITLE
How to create desktop app?

### ISSUE THREAD

**Issue by monkeysuffrage** [mimecorg/vuido#4]
Hi, I'm looking for info about creating desktop apps (windows exe/osx app)
Is this not working yet?

**Comment by mimecorg** [comment]
This isn't implemented yet, but I'm planning to do that. For now, you have to run the application by running Node with the path to your script and an argument. You can create a script which does that or, on Windows, you can create a shortut to node.exe with arguments.

**Comment by monkeysuffrage** [comment]
Thanks Michal,
If I wanted to distribute a windows app w/installer (innosetup), I guess I
could include node.exe - does that seem feasible?

**Comment by vieruu** [comment]
if you want to distribute a Windows app, for now use proton-native or electron because this project isn't stable right now and doesn't have that many features

**Comment by monkeysuffrage** [comment]
Hmm, Proton-native doesn't package windows apps yet either. I'm stuck with
electron for now I guess.

**Comment by vieruu** [comment]
use electron-vue
it has all the things you need

**Comment by mimecorg** [comment]
It's true, Vuido currently is work in progress, I have to implement the most important remaining controls first. But I'm planning to create a solution to package Vuido apps as seamlessly as possible.

The idea is to create a wrapper executable which will links Node as a shared library and will automatically run the script in the app subdirectory, pretty much like Electron does.

**Comment by monkeysuffrage** [comment]
Ok that sounds great. To  clarify my earlier comment about Electron, I
think Electron is great - it's just the size of the packaged installer that
I have an issue with and I was hoping this project might be a way to
address that. A 60M "Hello world" is just hard to get behind for me.

**Comment by mimecorg** [comment]
I agree completely, reducing the size of the package is the main motivation behind this project.

**Comment by TheJaredWilcurt** [comment]
@monkeysuffrage 

http://nwjs.io

**Pros of Electron:**
* Great name/marketing/branding
* Big ecosystem
* Good documentation
* Used by a few big name projects
* Backed by GitHub

**Cons of Electron:**
* Basically one person behind most of the code
* Doesn't take Linux support seriously
* Has 0 support for legacy OS's
* Resource Hog
* No way to protect your source code

**Cons of NW.js**
* Terrible Name/Branding/Marketing
* Small ecosystem
* Basically one person behind most of the code
* Everything you need from the documentation is available, but the site is clunky

**Pros of NW.js**
* Supports twice as many OS's including back to OSX 10.6 and XP
* Actually cares about proper Linux support
* Allows for protected source code
* Backed by Intel
* Updated within 24 hours of a Chromium or Node release
* Still a resource hog, but uses less RAM and disk space than Electron
* Smaller distribution sizes (I've gotten 25MB before on a windows Installer)
* Been around 5 years longer/used by tens of thousands of projects
* Assumes you want to create a desktop app, and not a node script with an optional UI.
* Super easy to get started with and a no-nonsense API

If you are looking for a production ready option today, NW.js or Electron are you best options, depending on if you value better technology or better ecosystem.

I look forward to Libui-Node becoming a viable 3rd option.

Here is a tutorial for getting started with NW.js:

* https://gitlab.com/TheJaredWilcurt/battery-app-workshop

and here is a simple Vue starter for NW.js with a bunch of tips around how to optimize for Desktop instead of Web:

* https://github.com/TheJaredWilcurt/vue-desktop-basic

**Comment by Loilo** [comment]
> I agree completely, reducing the size of the package is the main motivation behind this project.

Just to clarify this: executables created with Vuido (just like with [pkg](https://github.com/zeit/pkg)) would still have to include a copy of Node.js, right? So the simplest app would still hardly drop below 20 MB.

**Comment by mimecorg** [comment]
Yes, of course Node.js is required, but 20 MB is still much better than the size of Electron.

**Comment by TheJaredWilcurt** [comment]
Depending on OS and configuration

* **Electron:** 120-240 MB
* **NW.js:** 70-120 MB
* **LibUI-Node:** ~20 MB (speculation)

Not ground shaking, but a noticeable improvement.

**Comment by mimecorg** [comment]
I recently released the first version of [LaunchUI](https://github.com/mimecorg/launchui) which makes it easier to package and distribute applications using Vuido and libui-node in general. The package size is about 22 MB in case of the Windows 32-bit version.

**Comment by monkeysuffrage** [comment]
That looks interesting but I don't understand the instructions.
Where does the `launchui.download ` code go?
It feels like I'm supposed to do something in package.json but I can't
guess what.
Maybe you could make a hello world app?

**Comment by mimecorg** [comment]
You can use the [LaunchUI Packager](https://github.com/mimecorg/launchui-packager) API to automatically create a package, but you will need to write a little script to do that. You can then add the script to package.json. I'm planning to add command line support to LaunchUI Packager to make this easier.

Alternatively, you can manually download LaunchUI form the [Releases](https://github.com/mimecorg/launchui/releases) and replace the app/main.js script. It's described in the documentation.

**Comment by monkeysuffrage** [comment]
Sorry, I'm not clear on what I need to do to make `npm run download` work.
I save the script as 'download.js'? and then what?

**Comment by mimecorg** [comment]
You don't need to run `npm run download` unless you intend to build LaunchUI from sources.
